# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "the blog: zelazowy"
email: krzysztof.jonczyk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
the blog: zelazowy. news, tech, tips
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:/zelazowy.github.io" # the base hostname & protocol for your site
twitter_username: krzychjonczyk
github_username: zelazowy

# Google analytics
google_analytics: "UA-13163274-9"

# Build settings
markdown: kramdown
